// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package v1

import (
	"github.com/BradMichel/stori/internal/notifiers"
	"github.com/BradMichel/stori/pkg/aws"
	ses2 "github.com/BradMichel/stori/pkg/email/ses"
	"github.com/BradMichel/stori/pkg/validators"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/ses"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func Initialize() (*Handler, error) {
	emailNotificatorConfig, err := notifiers.NewEmailNotificatorConfig()
	if err != nil {
		return nil, err
	}
	accountSummaryEmailBuilder := notifiers.NewAccountSummaryEmailBuilder()
	v := aws.ConfigProvider()
	sessionSession, err := session.NewSession(v...)
	if err != nil {
		return nil, err
	}
	sesSES := ses.New(sessionSession, v...)
	client := ses2.New(sesSES)
	emailNotificator := NewEmailNotificator(emailNotificatorConfig, accountSummaryEmailBuilder, client)
	config, err := NewValidatorConfig()
	if err != nil {
		return nil, err
	}
	fs := ProvideRequestJSON()
	service, err := validators.New(config, fs)
	if err != nil {
		return nil, err
	}
	logger := logrus.New()
	handler := New(emailNotificator, service, logger)
	return handler, nil
}
