// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package v1

import (
	"github.com/BradMichel/stori/internal/summarizers"
	"github.com/BradMichel/stori/internal/transactions"
	"github.com/BradMichel/stori/pkg/aws"
	s3_2 "github.com/BradMichel/stori/pkg/aws/s3"
	"github.com/BradMichel/stori/pkg/aws/s3/downloader"
	sns2 "github.com/BradMichel/stori/pkg/aws/sns"
	"github.com/BradMichel/stori/pkg/validators"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/aws/aws-sdk-go/service/s3"
	"github.com/aws/aws-sdk-go/service/sns"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func Initialize() (*Handler, error) {
	v := aws.ConfigProvider()
	sessionSession, err := session.NewSession(v...)
	if err != nil {
		return nil, err
	}
	s3S3 := s3.New(sessionSession, v...)
	config, err := NewTransactionsBucketConfig()
	if err != nil {
		return nil, err
	}
	manager, err := s3_2.New(s3S3, config)
	if err != nil {
		return nil, err
	}
	downloaderDownloader, err := downloader.New(manager)
	if err != nil {
		return nil, err
	}
	s3Repository := transactions.NewS3Repository(downloaderDownloader)
	accountService := summarizers.NewAccountService()
	snsSNS := sns.New(sessionSession, v...)
	notifierConfig, err := NewNotifierConfig()
	if err != nil {
		return nil, err
	}
	notifier := sns2.New(snsSNS, notifierConfig)
	dynamoRepConfig, err := transactions.NewDynamoConfig()
	if err != nil {
		return nil, err
	}
	dynamoDB := dynamodb.New(sessionSession, v...)
	dynamoRepDep := transactions.NewDynamoDep(dynamoDB)
	dynamoRepository := transactions.NewDynamoRepository(dynamoRepConfig, dynamoRepDep)
	accountUseCase := summarizers.NewAccountUseCase(s3Repository, accountService, notifier, dynamoRepository)
	validatorsConfig, err := NewValidatorConfig()
	if err != nil {
		return nil, err
	}
	fs := ProvideRequestJSON()
	service, err := validators.New(validatorsConfig, fs)
	if err != nil {
		return nil, err
	}
	logger := logrus.New()
	handler := New(accountUseCase, service, logger)
	return handler, nil
}
