// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package v1

import (
	"github.com/BradMichel/stori/internal/accounts"
	"github.com/BradMichel/stori/pkg/aws"
	sns2 "github.com/BradMichel/stori/pkg/aws/sns"
	"github.com/BradMichel/stori/pkg/time"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/aws/aws-sdk-go/service/sns"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func Initialize() (*Handler, error) {
	repConfig, err := accounts.NewDynamoConfig()
	if err != nil {
		return nil, err
	}
	v := aws.ConfigProvider()
	sessionSession, err := session.NewSession(v...)
	if err != nil {
		return nil, err
	}
	dynamoDB := dynamodb.New(sessionSession, v...)
	repDep := accounts.NewDynamoDep(dynamoDB)
	dynamoRepository := accounts.NewDynamoRepository(repConfig, repDep)
	snsSNS := sns.New(sessionSession, v...)
	notifierConfig, err := NewNotifierConfig()
	if err != nil {
		return nil, err
	}
	notifier := sns2.New(snsSNS, notifierConfig)
	summarizerInitiator := accounts.NewSummarizerInitiator(dynamoRepository, notifier)
	service := time.New()
	logger := logrus.New()
	handler := New(summarizerInitiator, service, logger)
	return handler, nil
}
